//https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
const ISO_langs = {  
  name: ["Abkhazian","Afar","Afrikaans","Akan","Albanian","Amharic","Arabic","Aragonese","Armenian","Assamese","Avaric","Avestan","Aymara","Azerbaijani","Bambara","Bashkir","Basque","Belarusian","Bengali","Bihari languages","Bislama","Bosnian","Breton","Bulgarian","Burmese","Catalan, Valencian","Chamorro","Chechen","Chichewa, Chewa, Nyanja","Chinese","Chuvash","Cornish","Corsican","Cree","Croatian","Czech","Danish","Divehi, Dhivehi, Maldivian","Dutch, Flemish","Dzongkha","English","Esperanto","Estonian","Ewe","Faroese","Fijian","Finnish","French","Fulah","Galician","Georgian","German","Greek, Modern (1453–)","Guarani","Gujarati","Haitian, Haitian Creole","Hausa","Hebrew","Herero","Hindi","Hiri Motu","Hungarian","Interlingua (International Auxiliary Language Association)","Indonesian","Interlingue, Occidental","Irish","Igbo","Inupiaq","Ido","Icelandic","Italian","Inuktitut","Japanese","Javanese","Kalaallisut, Greenlandic","Kannada","Kanuri","Kashmiri","Kazakh","Central Khmer","Kikuyu, Gikuyu","Kinyarwanda","Kirghiz, Kyrgyz","Komi","Kongo","Korean","Kurdish","Kuanyama, Kwanyama","Latin","Luxembourgish, Letzeburgesch","Ganda","Limburgan, Limburger, Limburgish","Lingala","Lao","Lithuanian","Luba-Katanga","Latvian","Manx","Macedonian","Malagasy","Malay","Malayalam","Maltese","Maori","Marathi","Marshallese","Mongolian","Nauru","Navajo, Navaho","North Ndebele","Nepali","Ndonga","Norwegian Bokmål","Norwegian Nynorsk","Norwegian","Sichuan Yi, Nuosu","South Ndebele","Occitan","Ojibwa","Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic","Oromo","Oriya","Ossetian, Ossetic","Punjabi, Panjabi","Pali","Persian","Polish","Pashto, Pushto","Portuguese","Quechua","Romansh","Rundi","Romanian, Moldavian, Moldovan","Russian","Sanskrit","Sardinian","Sindhi","Northern Sami","Samoan","Sango","Serbian","Gaelic, Scottish Gaelic","Shona","Sinhala, Sinhalese","Slovak","Slovenian","Somali","Southern Sotho","Spanish, Castilian","Sundanese","Swahili","Swati","Swedish","Tamil","Telugu","Tajik","Thai","Tigrinya","Tibetan","Turkmen","Tagalog","Tswana","Tonga (Tonga Islands)","Turkish","Tsonga","Tatar","Twi","Tahitian","Uighur, Uyghur","Ukrainian","Urdu","Uzbek","Venda","Vietnamese","Volapük","Walloon","Welsh","Wolof","Western Frisian","Xhosa","Yiddish","Yoruba","Zhuang, Chuang","Zulu"],
  code2: ["ab","aa","af","ak","sq","am","ar","an","hy","as","av","ae","ay","az","bm","ba","eu","be","bn","bh","bi","bs","br","bg","my","ca","ch","ce","ny","zh","cv","kw","co","cr","hr","cs","da","dv","nl","dz","en","eo","et","ee","fo","fj","fi","fr","ff","gl","ka","de","el","gn","gu","ht","ha","he","hz","hi","ho","hu","ia","id","ie","ga","ig","ik","io","is","it","iu","ja","jv","kl","kn","kr","ks","kk","km","ki","rw","ky","kv","kg","ko","ku","kj","la","lb","lg","li","ln","lo","lt","lu","lv","gv","mk","mg","ms","ml","mt","mi","mr","mh","mn","na","nv","nd","ne","ng","nb","nn","no","ii","nr","oc","oj","cu","om","or","os","pa","pi","fa","pl","ps","pt","qu","rm","rn","ro","ru","sa","sc","sd","se","sm","sg","sr","gd","sn","si","sk","sl","so","st","es","su","sw","ss","sv","ta","te","tg","th","ti","bo","tk","tl","tn","to","tr","ts","tt","tw","ty","ug","uk","ur","uz","ve","vi","vo","wa","cy","wo","fy","xh","yi","yo","za","zu"],
  code3: ["abk","aar","afr","aka","sqi","amh","ara","arg","hye","asm","ava","ave","aym","aze","bam","bak","eus","bel","ben","bih","bis","bos","bre","bul","mya","cat","cha","che","nya","zho","chv","cor","cos","cre","hrv","ces","dan","div","nld","dzo","eng","epo","est","ewe","fao","fij","fin","fra","ful","glg","kat","deu","ell","grn","guj","hat","hau","heb","her","hin","hmo","hun","ina","ind","ile","gle","ibo","ipk","ido","isl","ita","iku","jpn","jav","kal","kan","kau","kas","kaz","khm","kik","kin","kir","kom","kon","kor","kur","kua","lat","ltz","lug","lim","lin","lao","lit","lub","lav","glv","mkd","mlg","msa","mal","mlt","mri","mar","mah","mon","nau","nav","nde","nep","ndo","nob","nno","nor","iii","nbl","oci","oji","chu","orm","ori","oss","pan","pli","fas","pol","pus","por","que","roh","run","ron","rus","san","srd","snd","sme","smo","sag","srp","gla","sna","sin","slk","slv","som","sot","spa","sun","swa","ssw","swe","tam","tel","tgk","tha","tir","bod","tuk","tgl","tsn","ton","tur","tso","tat","twi","tah","uig","ukr","urd","uzb","ven","vie","vol","wln","cym","wol","fry","xho","yid","yor","zha","zul"]
}

//https://tesseract-ocr.github.io/tessdoc/Data-Files.html
// Ordered by name
const tesseract_langs = {
  name:
    ["Afrikaans","Albanian","Amharic","Arabic","Assamese","Azerbaijani","Azerbaijani - Cyrillic","Basque","Belarusian","Bengali","Bosnian","Bulgarian","Burmese","Catalan; Valencian","Cebuano","Central Khmer","Cherokee","Chinese - Simplified","Chinese - Traditional","Croatian","Czech","Danish","Dutch; Flemish","Dzongkha","English","English, Middle (1100-1500)","Esperanto","Estonian","Finnish","French","French, Middle (ca. 1400-1600)","Galician","Georgian","Georgian - Old","German","German Fraktur","Greek, Ancient (-1453)","Greek, Modern (1453-)","Gujarati","Haitian; Haitian Creole","Hebrew","Hindi","Hungarian","Icelandic","Indonesian","Inuktitut","Irish","Italian","Italian - Old","Japanese","Javanese","Kannada","Kazakh","Kirghiz; Kyrgyz","Korean","Kurdish","Lao","Latin","Latvian","Lithuanian","Macedonian","Malay","Malayalam","Maltese","Marathi","Nepali","Norwegian","Oriya","Panjabi; Punjabi","Persian","Polish","Portuguese","Pushto; Pashto","Romanian; Moldavian; Moldovan","Russian","Sanskrit","Serbian","Serbian - Latin","Sinhala; Sinhalese","Slovak","Slovenian","Spanish; Castilian","Spanish; Castilian - Old","Swahili","Swedish","Syriac","Tagalog","Tajik","Tamil","Telugu","Thai","Tibetan","Tigrinya","Turkish","Uighur; Uyghur","Ukrainian","Urdu","Uzbek","Uzbek - Cyrillic","Vietnamese","Welsh","Yiddish"],
  code2:
    ["af","sq","am","ar","as","az",null,"eu","be","bn","bs","bg","my","ca",null,"km",null,null,null,"hr","cs","da","nl","dz","en",null,"eo","et","fi","fr",null,"gl","ka",null,"de",null,null,"el","gu","ht","he","hi","hu","is","id","iu","ga","it",null,"ja","jv","kn","kk","ky","ko","ku","lo","la","lv","lt","mk","ms","ml","mt","mr","ne","no","or","pa","fa","pl","pt","ps","ro","ru","sa","sr",null,"si","sk","sl","es",null,"sw","sv",null,"tl","tg","ta","te","th","bo","ti","tr","ug","uk","ur","uz",null,"vi","cy","yi"],
  code3:
    ["afr","sqi","amh","ara","asm","aze","aze_cyrl","eus","bel","ben","bos","bul","mya","cat","ceb","khm","chr","chi_sim","chi_tra","hrv","ces","dan","nld","dzo","eng","enm","epo","est","fin","fra","frm","glg","kat","kat_old","deu","frk","grc","ell","guj","hat","heb","hin","hun","isl","ind","iku","gle","ita","ita_old","jpn","jav","kan","kaz","kir","kor","kur","lao","lat","lav","lit","mkd","msa","mal","mlt","mar","nep","nor","ori","pan","fas","pol","por","pus","ron","rus","san","srp","srp_latn","sin","slk","slv","spa","spa_old","swa","swe","syr","tgl","tgk","tam","tel","tha","bod","tir","tur","uig","ukr","urd","uzb","uzb_cyrl","vie","cym","yid"]
}

async function getPageLanguage() {
  // Compact Language Detector (CLD)
  // https://github.com/CLD2Owners/cld2
  let language
  let htmlLang = document.documentElement.lang.split(/-|_/)[0]
  if ( htmlLang.length > 0 ) {    
    language = { isReliable: true, languages: [{ language: htmlLang, percentage: 99}] }
  } else {
    language = await browser.i18n.detectLanguage( document.documentElement.innerHTML )
  }
  language = language.languages[0].language
  language = ISO_langs.code3[ISO_langs.code2.indexOf( language )]
  if ( language ) {
    return language
  } else {
    console.warn("Language not detected, using default")
    return null
  }
}
"languages.js"